GET http://localhost:5000/test-mobile
Content-Type: application/json
Accept: application/json
Authorization: 6bcd2db7-80c4-4a8e-94f4-26683dd8583a
Cookie: user-role=%242b%2410%24o9fIinqE.W1zZCG86gnY1Od5cnnvJJh66oKLC0uXAD0CBzHYjo.B6

### ADMIN Update profile user
GET http://localhost:5000/api/admin/users
Content-Type: application/json
Accept: application/json
Authorization: 6bcd2db7-80c4-4a8e-94f4-26683dd8583a
Cookie: user-role=%242b%2410%24o9fIinqE.W1zZCG86gnY1Od5cnnvJJh66oKLC0uXAD0CBzHYjo.B6

### Register
POST http://localhost:5000/api/users
Content-Type: application/json
Accept: application/json
Authorization: 6bcd2db7-80c4-4a8e-94f4-26683dd8583a


{
  "username" : "aomrizky",
  "password" : "rahasia",
  "phone" : "08748399200"
}

### Login

POST http://localhost:5000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "usernameOrPhone" : "user1",
  "password" : "password123"
}


### Get Current User
### User 

GET http://localhost:5000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: e3565d32-a42a-4860-b293-fbf747d95302


### Update User
### User

PATCH http://localhost:5000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 66592e2a-a070-4a22-9b32-2cc8de6ec99b

{
  "username" : "aomrizky",
  "phone": "08748399200",
  "password": "rahasia"
}


### Logout
### User

DELETE http://localhost:5000/api/users/logout
Content-Type: application/json
Accept: application/json
Authorization: e3565d32-a42a-4860-b293-fbf747d95302



### Admin
### Detail data user

GET http://localhost:5000/api/admin/users/get-one?username=aomrizky
Content-Type: application/json
Accept: application/json
Authorization: 60b85aca-074f-465a-8e77-b07400b5850b
Cookie: user-role=%242b%2410%24D3WxNow2fiU%2FVs9Nt24QreEEia1d2FtmxUOGT9kk1jTnSFtCrGxDy


### Update data by name
### Admin

PATCH http://localhost:5000/api/admin/user/update?username=aomrizky
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
    "username": "aomrizky123",
    "phone": "08134343433",
    "role_id": 3
}


###
# Create UOM
POST http://localhost:5000/api/uom/create
Content-Type: application/json
Authorization: 36ee06f1-5098-4e25-a6b1-fe031805080b
Cookie: user-role=%242b%2410%24XTJMwEj4TIMhoKyikK40pOAtgTfSdD8Hlxoo.T4.p7BOeSvYVNbDK

{
  "unit": "Arang",
  "isDeleted": false
}

###

# Update UOM
PUT http://localhost:5000/api/uom/update/3
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e

{
  "unit": "Arang"
}

###

# Delete UOM
DELETE http://localhost:5000/api/uom/delete/3
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Get One UOM
GET http://localhost:5000/api/uom/get-one/1
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Get All Uom
GET http://localhost:5000/api/uom/get
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Create Waste Category
POST http://localhost:5000/api/waste-category/create
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e

{
  "category": "Bernadya",
  "isDeleted": false
}

###

# Update Waste Category
PUT http://localhost:5000/api/waste-category/update/6
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e

{
  "category": "Handphone",
  "isDeleted": true
}

###

# Delete Waste Category
DELETE http://localhost:5000/api/waste-category/delete/6
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Get One Waste Category
GET http://localhost:5000/api/waste-category/get-one/1
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Get All Waste Category
GET http://localhost:5000/api/waste-category/get
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


###
# Create Waste Type
POST http://localhost:5000/api/waste-type/create
Content-Type: application/json
Authorization: 21b43697-339e-4ed4-a7dc-d52955a066d7
Cookie: user-role=%242b%2410%24uCpuGtvwvgIFhoplh2u6v.Bl9H7Fq2ZtVjiuBTKqKuD%2FIOtS3uaH6

{
  "waste_category_id": 1,
  "type": "Plastic Bottle Tomorro"
}

###

# Update Waste Type
PUT http://localhost:5000/api/waste-type/update/8
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm

{
  "type": "Plastic Bottle Tomorro",
  "waste_category_id": 3,
  "isDeleted": false
}

###

# Delete Waste Type
DELETE http://localhost:5000/api/waste-type/delete/8
Authorization: 21b43697-339e-4ed4-a7dc-d52955a066d7
Cookie: user-role=%242b%2410%24uCpuGtvwvgIFhoplh2u6v.Bl9H7Fq2ZtVjiuBTKqKuD%2FIOtS3uaH6


###
# Get One Waste Type
GET http://localhost:5000/api/waste-type/get-one/1
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm


###
# Get All Waste Type
GET http://localhost:5000/api/waste-type/get
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm


### GET Price List

GET http://localhost:5000/api/pricelist/get
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


### CREATE Price List
POST http://localhost:5000/api/pricelist
Content-Type: application/json
Accept: application/json
Authorization: b0a36ebd-b1f2-44d3-8c84-dfcd5bf2bd1e
Cookie: user-role=%242b%2410%24LGMRfs2bmEneJz2QeO.UwuXC56kT6kCt5j89QbIBHFpEV5LGXEeDS

{
  "waste_type_id": 6,
  "uom_id": 2,
  "price": 10000,
  "isActive": true,
  "start_date": "2022-01-01T00:00:00.000Z",
  "end_date": "2022-12-31T00:00:00.000Z"
}


### UPDATE Price List BY WASTE TYPE ID AND UOM ID (6 waste type id and 2 uom id)
PUT  http://localhost:5000/api/pricelist/update/6/2
Content-Type: application/json
Accept: application/json
Authorization: 36ee06f1-5098-4e25-a6b1-fe031805080b
Cookie: user-role=%242b%2410%24XTJMwEj4TIMhoKyikK40pOAtgTfSdD8Hlxoo.T4.p7BOeSvYVNbDK

{
  "waste_type_id": 6,
  "uom_id": 3,
  "price": 15000,
  "isActive": true,
  "start_date": "2022-01-01T00:00:00.000Z",
  "end_date": "2022-12-31T00:00:00.000Z"
}


### DELETE PRICE LIST BY WASTE TYPE ID AND UOM ID
DELETE http://localhost:5000/api/pricelist/delete/6/2
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e



### GET ONE PRICE LIST BY WASTE ID AND UOM ID
GET http://localhost:5000/api/pricelist/get-one/8/2
Content-Type: application/json
Authorization: 270c565b-8502-4f7c-a4fa-3bba8e296343
Cookie: user-role=%242b%2410%24aOaoUVRhqfZS5zrkOjqCWOjapE%2FKakLET0%2FhB2GkSMNkKl4mcC90e


# CREATE Transactions
###
POST http://localhost:5000/api/transaction/create
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq

{
  "user_id": 1,
  "transaction_date": "2024-10-10T00:00:00.000Z",
  "total": 10000,
  "approved_by": 1
}

# READ Transactions
###
GET http://localhost:5000/api/transaction/list
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm


# Get One Transactions
###
GET http://localhost:5000/api/transaction/getOne/1
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq


# Update Transactions
###
PUT http://localhost:5000/api/transaction/update/1
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm

{
  "user_id": 2,
  "transaction_date": "2024-12-12T00:00:00.000Z",
  "total": 12000,
  "approved_by": 3
}


# Delete Transactions
###
DELETE http://localhost:5000/api/transaction/delete/1
Content-Type: application/json
Authorization: c8db002c-9133-4dce-a5df-8d23d1b8c7f0
Cookie: user-role=%242b%2410%24440VTKOn%2Fz1f0SipYF6oReR08wikDiCbb0PTBS3ET3TcQjgA5upqm


# CREATE Transactions Data
###
POST http://localhost:5000/api/transactionData/create
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq

{
  "transaction_id": 1,
  "waste_type_id": 3,
  "uom_id": 2,
  "quantity": 3,
  "price": 40000
}

# READ Transactions Data
###
GET http://localhost:5000/api/transactionData/list?transaction_id=2
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq


# Get One Transactions Data
###
GET http://localhost:5000/api/transactionData/getOne/2
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq


# Update Transactions Data
###
PUT http://localhost:5000/api/transactionData/update/2
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq

{
  "transaction_id": 1,
  "waste_type_id": 2,
  "uom_id": 2,
  "quantity": 2,
  "price": 22000
}

# Delete Transactions Data
###
DELETE http://localhost:5000/api/transactionData/delete/1
Content-Type: application/json
Authorization: f9d1a47f-d33b-4869-bf63-43f961b0809d
Cookie: user-role=%242b%2410%24H7%2FZfgnzfNnlBvpKr7W9p.GeKJd6%2FxVJZ2GxbHWfJW4YTYhQuRb%2Fq



# CREATE Article
###
POST http://localhost:5000/api/article/create
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "title": "Pengelolaan Bungkus Botol",
  "content": "Pentingnya pengelolaan Bungkus Botol.",
  "category": "Lingkungan",
  "isPublished": true,
  "created_by": "user1",
  "created_date": "2024-11-09T03:18:03.378Z",
  "article_order": 1
}

# READ Article
###
GET http://localhost:5000/api/article/list
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Get One Article
###
GET http://localhost:5000/api/article/getOne/2
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Update Article
###
PUT http://localhost:5000/api/article/update/2
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "title": "Pengelolaan Bungkus Botol Coba",
  "content": "Pentingnya pengelolaan Bungkus Botol.",
  "category": "Lingkungan",
  "isPublished": true,
  "created_by": "user1",
  "created_date": "2024-11-09T03:18:03.378Z",
  "article_order": 1
}

# Delete Article
###
DELETE http://localhost:5000/api/article/delete/2
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# CREATE Log Articles
###
POST http://localhost:5000/api/log-article/create
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "article_id": 2,
  "accessed_by": "user1",
  "accessed_time": "2024-11-09T13:20:30.378Z"
}

# READ Log Articles
###
GET http://localhost:5000/api/log-article/list
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Get One Log Articles
###
GET http://localhost:5000/api/log-article/getOne/2/user1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Update Log Articles
###
PUT http://localhost:5000/api/log-article/update/1/user1
Content-Type: application/json
Authorization: 1efdb2f5-6668-4f1e-aeee-0f3de3eda8c4
Cookie: user-role=%242b%2410%24KflxByPGJFbW2g4DAf9bru6ISR66iZDVFOJaXXH1eh5iLphVpOZnm

{
  "accessed_time_old": "2024-11-09T13:20:03.378Z",
  "accessed_time_new": "2024-11-09T13:20:30.378Z"
}

# Delete Log Articles
###
DELETE http://localhost:5000/api/log-article/delete/1/user1
Content-Type: application/json
Authorization: 1efdb2f5-6668-4f1e-aeee-0f3de3eda8c4
Cookie: user-role=%242b%2410%24KflxByPGJFbW2g4DAf9bru6ISR66iZDVFOJaXXH1eh5iLphVpOZnm


# CREATE Videos
###
POST http://localhost:5000/api/videos/create
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "title": "Pengelolaan Bungkus Botol",
  "description": "Pentingnya pengelolaan Bungkus Botol.",
  "duration": 400,
  "format": "mp4",
  "thumbnail_url": "https://example.com/thumbnail.jpg",
  "url": "https://example.com/video.mp4",
  "upload_date": "2024-11-09T03:18:03.378Z",
  "uploaded_by": "user1",
  "isActive": true,
  "video_order": 1
}

# READ Videos
###
GET http://localhost:5000/api/videos/list
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Get One Videos
###
GET http://localhost:5000/api/videos/getOne/1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Update Videos
###
PUT http://localhost:5000/api/videos/update/1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "title": "Pengelolaan Bungkus Botol",
  "description": "Pentingnya pengelolaan Bungkus Botol.",
  "duration": 350,
  "format": "mp4",
  "thumbnail_url": "https://example.com/thumbnail.jpg",
  "url": "https://example.com/video.mp4",
  "upload_date": "2024-11-09T03:18:03.378Z",
  "uploaded_by": "user1",
  "isActive": true,
  "video_order": 1
}

# Delete Article
###
DELETE http://localhost:5000/api/article/delete/1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# CREATE Log Videos
###
POST http://localhost:5000/api/log-videos/create
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "video_id": 1,
  "accessed_by": "user1",
  "accessed_time": "2024-11-09T13:22:30.378Z"
}

# READ Log Videos
###
GET http://localhost:5000/api/log-videos/list
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Get One Log Videos
###
GET http://localhost:5000/api/log-videos/getOne/1/user1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Update Log Videos
###
PUT http://localhost:5000/api/log-videos/update/1/user1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi

{
  "accessed_time_old": "2024-11-09T13:22:03.378Z",
  "accessed_time_new": "2024-11-09T13:22:29.378Z"
}

# Delete Log Videos
###
DELETE http://localhost:5000/api/log-videos/delete/1/user1
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Count Articles
### Test 1: Get daily count
GET http://localhost:5000/api/count/articles/2/2024-11-08
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


### Test 2: Get monthly count
GET http://localhost:5000/api/count/articles/2/2024-08
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


### Test 3: Get yearly count
GET http://localhost:5000/api/count/articles/2/2024
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi


# Count Videos
### Test 1: Get daily count
GET http://localhost:5000/api/count/videos/1/2024-11-09
Content-Type: application/json
Authorization: a841e297-d32a-478b-a439-bd34bd435e3e
Cookie: user-role=%242b%2410%24R6CgJPQ6mCKaYRKgFr7%2Fue9EEsovp0bYU237TFr723N0OmnPqgXoi



### Get All Payment Requests
GET http://localhost:5000/api/payment-requests
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Get Payment Request by ID
GET http://localhost:5000/api/payment-requests/1
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Create New Payment Request
POST http://localhost:5000/api/payment-requests
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 2,
    "request_date": "2024-01-01T00:00:00.000Z",
    "request_amount": 1000000,
    "payment_by": 2,
    "confirmation_status": "Waiting_For_Confirmation",
    "confirmation_date": "2024-01-05T00:00:00.000Z"
}

### Update Payment Request
PUT http://localhost:5000/api/payment-requests/4
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 2,
    "request_date": "2024-01-01T00:00:00.000Z",
    "request_amount": 1500000,
    "expected_payment_date": "2024-01-10T00:00:00.000Z",
    "payment_date": "2024-01-05T00:00:00.000Z",
    "payment_by": 2,
    "confirmation_status": "APPROVED",
    "confirmation_status": "Waiting_For_Confirmation",
    "confirmation_date": "2024-01-05T00:00:00.000Z"
}

### Delete Payment Request
DELETE http://localhost:5000/api/payment-requests/4
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Test Invalid Create (Missing Required Fields)
POST http://localhost:5000/api/payment-requests
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "request_amount": 1000000
}

### Test Invalid Create (Invalid Status)
POST http://localhost:5000/api/payment-requests
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "request_date": "2024-01-01T00:00:00.000Z",
    "request_amount": 1000000,
    "expected_payment_date": "2024-01-10T00:00:00.000Z",
    "payment_by": 2,
    "confirmation_status": "INVALID_STATUS"
}

### Test Get Non-existent Payment Request
GET http://localhost:5000/api/payment-requests/999
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Test Update Non-existent Payment Request
PUT http://localhost:5000/api/payment-requests/999
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "request_date": "2024-01-01T00:00:00.000Z",
    "request_amount": 1500000,
    "expected_payment_date": "2024-01-10T00:00:00.000Z",
    "payment_by": 2,
    "confirmation_status": "APPROVED"
}

### Test Create Duplicate Payment Request (Same user_id and payment_by)
POST http://localhost:5000/api/payment-requests
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "request_date": "2024-01-01T00:00:00.000Z",
    "request_amount": 1000000,
    "expected_payment_date": "2024-01-10T00:00:00.000Z",
    "payment_by": 2,
    "confirmation_status": "Success",
    "confirmation_date": "2024-01-05T00:00:00.000Z"
}

### Get All Waste Pickups
GET http://localhost:5000/api/waste-pickups
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Get One Waste Pickup
GET http://localhost:5000/api/waste-pickups/1
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Create New Waste Pickup
POST http://localhost:5000/api/waste-pickups
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "pick_up_date": "2024-11-25T10:00:00.000Z",
    "location": "Jl. Contoh No. 123, Jakarta",
    "status": "Scheduled"
}

### Update Waste Pickup
PUT http://localhost:5000/api/waste-pickups/1
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "pick_up_date": "2024-11-26T10:00:00.000Z",
    "location": "Jl. Contoh No. 123, Jakarta",
    "status": "Completed"
}

### Delete Waste Pickup
DELETE http://localhost:5000/api/waste-pickups/1
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK

### Test Invalid Status
POST http://localhost:5000/api/waste-pickups
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "pick_up_date": "2024-11-25T10:00:00.000Z",
    "location": "Jl. Contoh No. 123, Jakarta",
    "status": "INVALID_STATUS"
}

### Test Invalid User ID
POST http://localhost:5000/api/waste-pickups
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 999999,
    "pick_up_date": "2024-11-25T10:00:00.000Z",
    "location": "Jl. Contoh No. 123, Jakarta",
    "status": "PENDING"
}

### Test Missing Required Fields
POST http://localhost:5000/api/waste-pickups
Authorization: 90dcb747-b5af-49d7-b91e-4e7df2c03ba2
Cookie: user-role=%242b%2410%24LLzah8QH8nQzE70aC8%2FWLeznJXdfNDByduCeWXWEYkmijTD8IhvVK
Content-Type: application/json

{
    "user_id": 1,
    "location": "Jl. Contoh No. 123, Jakarta"
}

### Get Dashboard Data (Default - Current Year)
GET http://localhost:5000/api/dashboard
Content-Type: application/json
Authorization: 95d7550b-a24f-4a14-8fc6-039bb6dfed8d
Cookie: user-role=%242b%2410%24h7vo8mZZKwbMXSdT30q7v.cOgfLHukaC6YYY4ZAYox4VrKsbiRTO2

### Get Dashboard Data with Custom Date Range
GET http://localhost:5000/api/dashboard?startDate=2024-01-01&endDate=2024-11-30
Content-Type: application/json
Authorization: 95d7550b-a24f-4a14-8fc6-039bb6dfed8d
Cookie: user-role=%242b%2410%24h7vo8mZZKwbMXSdT30q7v.cOgfLHukaC6YYY4ZAYox4VrKsbiRTO2